# "jju" stands for "json/json5 utils"
name: jju

version: 1.4.0
description: a set of utilities to work with JSON / JSON5 documents

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

repository:
  type: git
  url: git://github.com/rlidwka/jju

bugs:
  url: https://github.com/rlidwka/jju/issues

homepage: http://rlidwka.github.io/jju/

devDependencies:
  mocha: '6.1.4'
  js-yaml: '13.3.1'
  eslint: '5.16.0' # TODO: update this

scripts:
  test: make test
  lint: make lint

keywords:
  - json
  - json5
  - parser
  - serializer
  - data

license: MIT
